version: '2'
services:
  monolithic:
    image: heinminhsoe/monolithic
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://monolithic-mysql:3306/monolithic?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
      - JHIPSTER_METRICS_LOGS_ENABLED=false
    ports:
      - '8080:8080'
  monolithic-mysql:
    image: 'mysql:8.0.20'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=monolithic
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  prometheus:
    extends:
      file: prometheus.yml
      service: prometheus

  alertmanager:
    extends:
      file: prometheus.yml
      service: alertmanager

  grafana:
    extends:
      file: prometheus.yml
      service: grafana

volumes:
  prometheus_data: {}
  grafana_data: {}
